input_article = "gen/speech.txt"
output_dir = "gen/output"
model_name = "F5TTS_v1_Base"
max_sentence_length = 200

# Default/main voice points to tender
[voices.main]
ref_audio = "voices/nice/happy.wav"
ref_text = ""
speed = 0.9

[voices.caixukun]
ref_audio = "voices/nice/caixukun.wav"
ref_text = ""
speed = 1.0

[voices.guimi]
ref_audio = "voices/nice/guimi.wav"
ref_text = ""
speed = 1.0

[voices."happy"]
ref_audio = "voices/nice/happy.wav"
ref_text = ""
speed = 0.9

# f-a voices
[voices."tender"]
ref_audio = "voices/f-a/tender.wav"
ref_text = ""
speed = 1.0


[voices."confused"]
ref_audio = "voices/f-a/confused.wav"
ref_text = ""
speed = 0.9

[voices."sad"]
ref_audio = "voices/f-a/sad.wav"
ref_text = ""
speed = 1.0

[voices."friendly"]
ref_audio = "voices/f-a/friendly.wav"
ref_text = ""
speed = 1.0

[voices."angry"]
ref_audio = "voices/f-a/angry.wav"
ref_text = ""
speed = 1.0

[voices."fear"]
ref_audio = "voices/f-a/fear.wav"
ref_text = ""
speed = 1.0

# f-b voices
[voices."haoya"]
ref_audio = "voices/f-b/haoya.wav"
ref_text = ""
speed = 1.0

[voices."heng"]
ref_audio = "voices/f-b/heng.wav"
ref_text = ""
speed = 1.0

[voices."wa"]
ref_audio = "voices/f-b/wa.wav"
ref_text = ""
speed = 1.1

# f-c voices
[voices.heihei]
ref_audio = "voices/f-c/heihei.wav"
ref_text = ""
speed = 0.6

[voices."xiaoshagua"]
ref_audio = "voices/f-c/xiaoshagua.wav"
ref_text = ""
speed = 1.0

[voices."shiya"]
ref_audio = "voices/f-c/shiya.wav"
ref_text = ""
speed = 1.0

[voices.a]
ref_audio = "voices/a.wav"
ref_text = ""
speed = 0.9

[voices.serena]
ref_audio = "voices/serena.wav"
ref_text = ""
speed = 1.0


# man
[voices.man]
ref_audio = "voices/man/normal.wav"
ref_text = ""
speed = 1.0

[voices."man.angry"]
ref_audio = "voices/man/angry.wav"
ref_text = ""
speed = 1.0

[voices."man.happy"]
ref_audio = "voices/man/happy.wav"
ref_text = ""
speed = 1.0

[voices."man.sad"]
ref_audio = "voices/man/sad.wav"
ref_text = ""
speed = 1.0

[voices."man.surprise"]
ref_audio = "voices/man/surprise.wav"
ref_text = ""
speed = 1.0

[voices."man.control"]
ref_audio = "voices/man/control.wav"
ref_text = ""
speed = 1.0

# vivian
[voices.vivian]
ref_audio = "voices/vivian/normal.wav"
ref_text = ""
speed = 1.0

[voices."vivian.angry"]
ref_audio = "voices/vivian/angry.wav"
ref_text = ""
speed = 1.0

[voices."vivian.happy"]
ref_audio = "voices/vivian/happy.wav"
ref_text = ""
speed = 1.0

[voices."vivian.sad"]
ref_audio = "voices/vivian/sad.wav"
ref_text = ""
speed = 1.0

[voices."vivian.surprise"]
ref_audio = "voices/vivian/surprise.wav"
ref_text = ""
speed = 1.0

[voices."vivian.control"]
ref_audio = "voices/vivian/control.wav"
ref_text = ""
speed = 1.0
